baseURL: "https://hugo.lukasljl.de"
languageCode: "en-us"
title: Cloud-Computing
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production
    title: Cloud-Computing
    description: "ExampleSite description"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    DateFormat: "2. January 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: github
          url: "https://github.com/lukasljl"
        - name: twitter
          url: "https://twitter.com/lukas_ljl"

    editPost:
        URL: "https://github.com/LukasLJL/cloud-computing-project/tree/master/content/posts"
        Text: "Suggest Changes"
        appendFilePath: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: posts
          name: posts
          url: /posts/
          weight: 1  
        - identifier: categories
          name: categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: tags
          url: /tags/
          weight: 3
