name: CI/CD-Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          submodules: true

      - name: Set SHA-Commit Tag
        id: sha
        run: echo ::set-output name=commit_hash::${GITHUB_SHA::8}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.98.0'

      - name: Build Hugo
        run: hugo --minify

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/lukasljl/cloud-computing-project:${{ steps.sha.outputs.commit_hash }}
            ghcr.io/lukasljl/cloud-computing-project:latest
          labels: LukasLJL/cloud-computing-project

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set SHA-Commit Tag
      id: sha
      run: echo ::set-output name=commit_hash::${GITHUB_SHA::8}

    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: set image --record deployment/hugo-www-app -n cloud-computing hugo-www-app=ghcr.io/lukasljl/cloud-computing-project:${{ steps.sha.outputs.commit_hash }}
